### ISSUE TITLE
Warning, Notice and Deprecated in J3.6.x+PHP7

### ISSUE THREAD

**Issue by sshcli** [gibilogic/simpleregistration#2]
#### Steps to reproduce the issue
1. Extract username = YES
2. Autologin = YES
3. Create menu item GiBi SimpleRegistration » Registration form
4. Go to menu item
#### Expected result

I should't get any warning, notice or deprecated
#### Actual result

Warning: Declaration of SimpleregistrationController::display() should be compatible with JControllerLegacy::display($cachable = false, $urlparams = Array) in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/controller.php on line 15

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 27

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 28

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 29

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 30

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 31

Deprecated: Non-static method JApplicationSite::getMenu() should not be called statically in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 39

Deprecated: Non-static method JApplicationCms::getMenu() should not be called statically in /home/healthca/public_html/webpage.gq/libraries/cms/application/site.php on line 272

Notice: Undefined variable: this in /home/healthca/public_html/webpage.gq/libraries/cms/application/cms.php on line 434

Notice: Only variables should be assigned by reference in /home/healthca/public_html/webpage.gq/components/com_simpleregistration/views/registrationform/view.html.php on line 39
#### System information (as much as possible)

Joomla version: 3.6.3-rc1
Php version: 7.0.9
Database version: 5.6.33

**Comment by zanardigit** [comment]
@sshcli thank you for reporting. I will have a look.

**Comment by sshcli** [comment]
yw

**Comment by zanardigit** [comment]
Just discovered that `master` branch was way behind in development, so I pushed all latest commits. Recap:

* tag `v3.0` is the master as it was until a few minutes ago
* tag `v3.1` is an intermediate release that was never pushed on GitHub
* `master` is for version 3.2 (active version)

Please pull and build latest version, notices and warnings should go away.

**Comment by sshcli** [comment]
Ok.
Please update this link:
https://extensions.gibilogic.com/downloads/gibi-simpleregistration

**Comment by sshcli** [comment]
The download link from your website is broken:
https://extensions.yegods.it/simpleregistration/simpleregistration-3-2/pkg_simpleregistration_v3-2.0_FREE.zip?format=zip

**Comment by zanardigit** [comment]
Thank you for letting me know. It has been fixed now.

Sorry but I'll have to close this repository now, as the code has been moved elsewhere.
